name: Generate and deploy static documentation site
on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  generate_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20.5
      - name: Generate the static site
        run: |
          mkdir docs/
          npx @redocly/cli build-docs src/trebol-api.json --output=docs/index.html
      - name: Upload static site as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'
  deploy_docs:
    needs: generate_docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
